name: CUDA Memory Leak Check

on:
  pull_request:


concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.sha }}-${{ github.event_name == 'workflow_dispatch' }}
  cancel-in-progress: true

jobs:
  pull:
    name: pull
    uses: ./.github/workflows/pull.yml
    with:
      mem-leak: true
    secrets: inherit

  trunk:
    name: trunk
    uses: ./.github/workflows/trunk.yml
    with:
      mem-leak: true
    secrets: inherit

  periodic:
    name: trunk
    uses: ./.github/workflows/periodic.yml
    with:
      mem-leak: true
    secrets: inherit
